spring:
  profiles:
    active: dev
  rabbitmq:
    host:  paascloud-mq-rabbit
    port: 5672
    username: '{cipher}AQBpZhSh52BJZNb5NSk+IvRqKv5K6HCL14+fzMSC+6TDXUU1xH9bYs2kt3QCgsTry+ID3kMPNomLjQXfQHbCTh3dxClmdiu3b9kKZMbmmM0sE+CufR1EOXcGVq1OCy6+tFD4cxGjrIqPqs0dplWS+cZlNQxwe+By67RDIq3Yi0Bqz+PRTcBbttUKg2yZSUqR0TMhO0GSPmDadWV+CQLKEPDRFXzbIPYIID4n6I4aEcH/bSU3dqBCKLOz65/xhY3g2/3CBwpYwqlhiVCJRRQSyAeLUdJuwHxoyQ/nfSOKy9q25rYD7OASGIHLDBFKXdLfhcKVyzMGt3qv7DJkoIFe17kLwg/Ae/TyonzBTsr8PkR6PwcY2eRJ7GkW8aXa0qsOfWo='
    password: '{cipher}AQBpZhSh52BJZNb5NSk+IvRqKv5K6HCL14+fzMSC+6TDXUU1xH9bYs2kt3QCgsTry+ID3kMPNomLjQXfQHbCTh3dxClmdiu3b9kKZMbmmM0sE+CufR1EOXcGVq1OCy6+tFD4cxGjrIqPqs0dplWS+cZlNQxwe+By67RDIq3Yi0Bqz+PRTcBbttUKg2yZSUqR0TMhO0GSPmDadWV+CQLKEPDRFXzbIPYIID4n6I4aEcH/bSU3dqBCKLOz65/xhY3g2/3CBwpYwqlhiVCJRRQSyAeLUdJuwHxoyQ/nfSOKy9q25rYD7OASGIHLDBFKXdLfhcKVyzMGt3qv7DJkoIFe17kLwg/Ae/TyonzBTsr8PkR6PwcY2eRJ7GkW8aXa0qsOfWo='
  redis:
    host: paascloud-db-redis
    password: '{cipher}AQBwKsuxplHAIMIV0Z+aJ+X5MpFPOP8NmxTo/XwFdYZ2k+RPck2Xo7011ku09BQI4ReqWXMmWL1IYxuNVnhEV7ol9NElMOjceuIsI1RON82nVeaO0zFTyibF7Ik1/JM0C4JGSgAblXGmWTVqsnb9GQA9KFFju1+YWnIEBdenBfNT/g7/gkZGZVdfZYJFBIjLL0hgmOs+zsct6jb1PO5cRqeBVX575FP3q1KUtwIBc4T/a2OpyivOitPfhUyuaCMpwOwprZtMarxkzRcaMIzXPVRRnMNbOIrb7HWtNwYlmbXC8qs9+uzmUWFnnbylRLErFI4AMGqVbOROaCzV20pXj0Lb/dULym+bjhl//AEThgqCUfJlcMENVnZm9xEXZxO5iSc='
    port: 6379
    timeout: 0
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: '{cipher}AQBwKsuxplHAIMIV0Z+aJ+X5MpFPOP8NmxTo/XwFdYZ2k+RPck2Xo7011ku09BQI4ReqWXMmWL1IYxuNVnhEV7ol9NElMOjceuIsI1RON82nVeaO0zFTyibF7Ik1/JM0C4JGSgAblXGmWTVqsnb9GQA9KFFju1+YWnIEBdenBfNT/g7/gkZGZVdfZYJFBIjLL0hgmOs+zsct6jb1PO5cRqeBVX575FP3q1KUtwIBc4T/a2OpyivOitPfhUyuaCMpwOwprZtMarxkzRcaMIzXPVRRnMNbOIrb7HWtNwYlmbXC8qs9+uzmUWFnnbylRLErFI4AMGqVbOROaCzV20pXj0Lb/dULym+bjhl//AEThgqCUfJlcMENVnZm9xEXZxO5iSc='
    password: '{cipher}AQBok7QIOmnx1TgD23c9It6tLDZIFrUrhiS1to6KLLrAEX4Dn52WF/owj9taLulKwTWOAOG61lTl8PMme0y1eFphQYrqgCr7Sz2quChv4oo2d2s1pJCK1xjC+Q/+VFktLniYJJGVjOuKZpkb79YQ2ASaKLPOm2raH7+nCUL2LAMcGY2s+5RFjhPeINLYwODTr8IiH1ak2UMai27NyfYe8x9wn7DJZ+WdyT7c6NntxRkvahzzm9ca5CW97uiugmBZW7rDM+l45zThUYJQDB3wcCzCCTwO8lt/SpNVn0IWp71uKrcmIpTOXnxpm6AB3WZ9rlHDFPm7TxWcB/b4eL5LkAi9BL9CF98e0eZriqlPKe7foMrgZxcMDmTQkKzG+WiPUio='
    type: com.alibaba.druid.pool.DruidDataSource
    initial-size: 10
    min-idle: 10
    max-active: 20
    test-on-borrow: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://root:root@paascloud-eureka:8761/eureka/
paascloud:
  server:
    eureka:
      port: 8761
      hostname: paascloud-eureka
      serviceUrl: http://root:root@paascloud-eureka:8761/eureka/
    discovery:
      port: 8080
      hostname: paascloud-discovery
      serviceUrl: http://admin:admin@paascloud-discovery:8080
    gateway:
      port: 80
      hostname: paascloud-gateway
    monitor:
      port: 8010
      hostname: paascloud-monitor
      serviceUrl: http://paascloud-monitor:8010
    zipkin:
      port: 8020
      hostname: paascloud-zipkin
      serviceUrl: http://paascloud-zipkin:8020
    provider:
      ehc:
        port: 8040
        hostname: paascloud-provider-ehc
      mdc:
        port: 8030
        hostname: paascloud-provider-mdc
      omc:
        port: 8050
        hostname: paascloud-provider-omc
      opc:
        port: 8070
        hostname: paascloud-provider-opc
      ptc:
        port: 8060
        hostname: paascloud-provider-ptc
      uac:
        port: 8000
        hostname: paascloud-provider-uac
    web:
      mall:
        port: 9000
        hostname: paascloud-web-mall
  auth:
    jwt:
      expiredRemainMinutes: 20
      expiredMinutes: 120
  mail:
    host: smtp.sina.cn
    username: '{cipher}AQAR7CGRsNJ9tGKCKuv3Y1Tn6DWUD4P5Xzp+0LeqGg5qfjsRi+fL/EGEWvzeysKuH1ChLnSZ1T5hrJeBoImdmltSkN5iPZqjBJs6CAm48ksst39F6KaPyNmTqjU0UheTTeJkZoQxdtA/3OXxVWazHRZK7/34KLStohlPav1K3qAnkDj/Y62tKT67qhsAPTCOnLaaH6ab6NpX0h95mE0yz0w6070iHDDeFrAef627Crwh4QLKieSQg005zwVgYED/dPi4/PRNQWoC3brPUURloVCKs1EYaru8NmJ9bKMzURmuI74A1rSI/I7rGm3AE6BURHihnUnuzBehUgsSa8G0zN2zh2awhkyuBSJLn+eMmfxHH601vZwG7pDkQQBHJ9rwNxP5fbEeow+sWw9qa/nBls+K'
    password: '{cipher}AQAXyZKaUjiYntQ+bxlDpDbYQmZv/ZePZurJ//xyZJhSL/GXNi581996S3cD8Wyy9UglzebomyOH/bkZ4+mhNrpSIJw4sD2cGuuiyIfIdpoffyuMQi5qJcWOcbDj4g03Wz6AzPiXcG5bSV6vW41LJ18ttVbXXEmRiR0CahjNsYzTTc+PFAIT2Sm9GgS6eq9x1g+njQBrRN52G1tDQsruy5cT0gk8j2kG1Ysof/KTYfjhMsfWzRMYz3nEs5+csWx73DCsXMIl5F1oy/sWCkdJn5SBP+QtTfCcOu58HoXjwjoD8LW89V5F/BWR2TpwvCfdhEG0PwCMIDS4X6E4p9qP6trfij8uls0Rx8+No8fdrNtW3TvGM/pLbFk26Kv4r65Itic='
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          timeout: 2500
          starttls:
            enable: true
            required: true
  aliyun:
    key:
      accessKeyId: '{cipher}AQB6Kbido8WBy4joIVC4kuQuNsnm3mAYETILJi2Z+BQRVWcqxH2u4B+GoQJiiPF3bw04xXkqdj6XoQTwlZvsf5I/h341M3HSjygNmCYeq6iQxNyc/YD7qzX+1ds84dTR660XSWd6R0M3ywmh6W1Dc7bucGUGH9Uix8EkAnkDs+e6oBZrpba5EK62k3jVRfmufLk66H8XBSLH2zx0taFqjRLOUJrkMpSHluwLuQ2ojbhOKNRywH63zdC3IlDjcFqn0Ahu/+3RaNBrG9NIeGbzVZxmREYYk+4E7KBYhYxOucYPK5CCVGoY3QXWPKD1Jk+dy6LlzIY05UscQIbhnN9JeBO7UF+pymeTqu5BO0S59r8+rlzjWG8lw4hYy9UDU7kCK6zHYR/6uhgNuIW0lzLdwbgs'
      accessKeySecret: '{cipher}AQAse5xkCDLmnLLjPeNib9N0SEUCWs6S0CRGEzTQE46E73PcuK9INdvHjd1Zh2eg/5DnlXVlLiaeJcfRWKgVQk1YkIjxjwUiGXP4rPkd5BhhUiX3+1STs6NE79y3hFRWFpsuFqnoct2T+Ahg2LaBSB/GfNB1ToytbtRfdxd399SX+to0WIzLMmBlzCOL+C6wClUVusHGbncDCvnzzxKS/1Rp60gKBdC/DbePggLIlaQu3jCfhw05VIjB6x9LSmKIXTKSNFrggoNlgfabHheVfw/sc7EBGb54D7V91pCshbnSzMSdSSZ0O625Npp889fQa1ia4rIk08WXf8p6stmJn+sqQvyYQ+Fo87ZGbq42VS4s5DKd1Hzsndec1sGXLrkyZDwCb1DsUkDUceEYEBVbEzkB'
    rocketMq:
      namesrvAddr: paascloud-mq-rocket:9876
    sms:
      signName: "快乐学习网"
      regionId: cn-beijing
      endpoint:
      endpointName: cn-beijing
      product: '{cipher}AQA7u26JNrD0HwL9I0AVyPHAxVhqMlphW4vjGjhW+V0qoTliek9Pb1xdfbIGhzGtVOPfyFg1x3IU84wgurS9WZycFLu35W36hMC/ZayvWUGXzcSQMJqBw7sGz0hSG3thJyN4/cYRGjhmuF0FaxIqSBCxxSVav/rpVyCLXlQu4Yr3dKmcyTnQBgVMcJ1573mxkOv59ItjiyQM+wZ2rBupKlcjEml30i+xGdNKZVHektuffzIjSSWMwfgd5vSb0eLuW9m55mR0lnFxVhhZobctUWKTtF6RUidJsjexLaioMjPGMS0txpHP57Gq2NVkgbi7HsHK8iTPQg2LJ2C4kFoqKmgzvzrsZEhCb9VyNVJ5+JNoZJYfIGyimxokpBhR/glILbA='
      domain: dysmsapi.aliyuncs.com
  qiniu:
    key:
      accessKey: '{cipher}AQAnxcpPlUslRTOAv0cgz7n4DPOWH8BK9yhfpd6MVIIaMpU6NYU3ADBn2rxxVJGjKvKjtqjE4sWOn1OtYLa3NTM5R31f7HQn26EYxhSyy6cNO00PnpIpDpMtV+ch3x94bdgWSLZi3zNhZ6P/kdPoKC4Ji8CYPgHvPI2mWQ/WnKWASCmrg3EtwGBH+E8ViQ3gVpgF76wnQwMSSFor2k5yiOEtH1HaPWFW0SgdHNu24YLXlj8nb2t5pBTTZmDr+zoC4hx3jlu4sObtn4G3XKRVjdz/+9EWMBVQ6P2Tbbp8l3XkXzT0mO0vAULSLfKno/coYoUTMbfXYQ82LQJlkH4EDm3Y56+20rbGHd6Fpl1K4HeTXO8WPBoH/bRYB6mKjVxHRS+hYFWMzuTv7STX9g5KqIO9Sy/8rp6pSwtpRWXckAqj8A=='
      secretKey: '{cipher}AQBRPHH+JQGKuGd4UreIdYyEDOx4lFG921nOTBRI//QIfkhrTuBoKAW/9H+80nuICW7156sqBhjZhecNJH7PRcAhRzKNg+YRpW1h7EGcPS1XFeCN4i12Dg+GQZhwqLUL1lvYxgLm9nR6O0xTJkmns1jy5NyPOxVy0eQO22oSEAENfg/xNir0+/75LEXXIf5qD2fZCHF/8/BWPt5hS9AIWXLOgB8qwxGlexKRSvlyVZiCrBn0WvgxwYvNrwUIJGEuDXYu3qtogdOfYg3D1UgovG0QqHUAYykG8YSuLPqbkJTiwKaUm+IgacBHiBF3CDel0lF7LfXfuxuViigl8ac5mhM1MDknIyzBZ+1pHxyVoXA+8/kguKZtc+VzLcsYgmAm+/jBT7yRMDUwkpDAmExZrdZQ6IqBNws8R3Y8qMaoEeeRFA=='
    oss:
      privateHost: '{cipher}AQA7u26JNrD0HwL9I0AVyPHAxVhqMlphW4vjGjhW+V0qoTliek9Pb1xdfbIGhzGtVOPfyFg1x3IU84wgurS9WZycFLu35W36hMC/ZayvWUGXzcSQMJqBw7sGz0hSG3thJyN4/cYRGjhmuF0FaxIqSBCxxSVav/rpVyCLXlQu4Yr3dKmcyTnQBgVMcJ1573mxkOv59ItjiyQM+wZ2rBupKlcjEml30i+xGdNKZVHektuffzIjSSWMwfgd5vSb0eLuW9m55mR0lnFxVhhZobctUWKTtF6RUidJsjexLaioMjPGMS0txpHP57Gq2NVkgbi7HsHK8iTPQg2LJ2C4kFoqKmgzvzrsZEhCb9VyNVJ5+JNoZJYfIGyimxokpBhR/glILbA='
      publicHost: '{cipher}AQA7u26JNrD0HwL9I0AVyPHAxVhqMlphW4vjGjhW+V0qoTliek9Pb1xdfbIGhzGtVOPfyFg1x3IU84wgurS9WZycFLu35W36hMC/ZayvWUGXzcSQMJqBw7sGz0hSG3thJyN4/cYRGjhmuF0FaxIqSBCxxSVav/rpVyCLXlQu4Yr3dKmcyTnQBgVMcJ1573mxkOv59ItjiyQM+wZ2rBupKlcjEml30i+xGdNKZVHektuffzIjSSWMwfgd5vSb0eLuW9m55mR0lnFxVhhZobctUWKTtF6RUidJsjexLaioMjPGMS0txpHP57Gq2NVkgbi7HsHK8iTPQg2LJ2C4kFoqKmgzvzrsZEhCb9VyNVJ5+JNoZJYfIGyimxokpBhR/glILbA='
  alipay:
    callback:
      url: http://dev-api.paascloud.net/omc/pay/alipayCallback
    qrCode:
      pcPath: E:/File/alipay/QRCode
      qiniuPath: alipay/QRCode/
